# Generated by Django 4.2.5 on 2023-10-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
